/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminQuestion { 
    readonly id?: number;
    readonly image?: string;
    correctAnswer: AdminQuestion.CorrectAnswerEnum;
    questionLevel: number;
}
export namespace AdminQuestion {
    export type CorrectAnswerEnum = 'left' | 'right';
    export const CorrectAnswerEnum = {
        Left: 'left' as CorrectAnswerEnum,
        Right: 'right' as CorrectAnswerEnum
    };
}

