/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Questionary } from './questionary';


export interface InlineResponse2004 { 
    next?: string | null;
    previous?: string | null;
    count: number;
    results: Array<Questionary>;
}

