/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoryLine } from './historyLine';


export interface InlineResponse200 { 
    next?: string | null;
    previous?: string | null;
    count: number;
    results: Array<HistoryLine>;
}

