/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Questionary { 
    readonly id?: number;
    perinealAreaPain: boolean;
    vulvaPain: boolean;
    clitorisPain: boolean;
    bladderPain: boolean;
    painFrequency?: Questionary.PainFrequencyEnum | null;
    peePain: boolean;
    sexualRelationsPain?: boolean;
    painIntensity?: number | null;
    stopDoingThings: Questionary.StopDoingThingsEnum;
    thinkSymptoms: Questionary.ThinkSymptomsEnum;
    sameHealthLife: Questionary.SameHealthLifeEnum;
    user?: number | null;
}
export namespace Questionary {
    export type PainFrequencyEnum = 'never' | 'rarely' | 'sometimes' | 'many times' | 'usually' | 'always';
    export const PainFrequencyEnum = {
        Never: 'never' as PainFrequencyEnum,
        Rarely: 'rarely' as PainFrequencyEnum,
        Sometimes: 'sometimes' as PainFrequencyEnum,
        ManyTimes: 'many times' as PainFrequencyEnum,
        Usually: 'usually' as PainFrequencyEnum,
        Always: 'always' as PainFrequencyEnum
    };
    export type StopDoingThingsEnum = 'none' | 'a little' | 'some' | 'lot';
    export const StopDoingThingsEnum = {
        None: 'none' as StopDoingThingsEnum,
        ALittle: 'a little' as StopDoingThingsEnum,
        Some: 'some' as StopDoingThingsEnum,
        Lot: 'lot' as StopDoingThingsEnum
    };
    export type ThinkSymptomsEnum = 'none' | 'a little' | 'some' | 'lot';
    export const ThinkSymptomsEnum = {
        None: 'none' as ThinkSymptomsEnum,
        ALittle: 'a little' as ThinkSymptomsEnum,
        Some: 'some' as ThinkSymptomsEnum,
        Lot: 'lot' as ThinkSymptomsEnum
    };
    export type SameHealthLifeEnum = 'charmed' | 'very satisfied' | 'satisfied' | 'confused' | 'dissatisfied' | 'discontent' | 'fatal';
    export const SameHealthLifeEnum = {
        Charmed: 'charmed' as SameHealthLifeEnum,
        VerySatisfied: 'very satisfied' as SameHealthLifeEnum,
        Satisfied: 'satisfied' as SameHealthLifeEnum,
        Confused: 'confused' as SameHealthLifeEnum,
        Dissatisfied: 'dissatisfied' as SameHealthLifeEnum,
        Discontent: 'discontent' as SameHealthLifeEnum,
        Fatal: 'fatal' as SameHealthLifeEnum
    };
}

