/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuestionLevel { 
    readonly questions?: Array<number>;
    readonly id?: number;
    level: number;
    averageDuration?: number | null;
    durationThreshold?: number | null;
    readonly str?: string;
}

