/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileCreateSerializers { 
    readonly id?: number;
    sex: UserProfileCreateSerializers.SexEnum;
    years: number;
    weight: number;
    heigh: number;
    user: number;
}
export namespace UserProfileCreateSerializers {
    export type SexEnum = 'male';
    export const SexEnum = {
        Male: 'male' as SexEnum
    };
}

