/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    readonly authToken?: string;
    readonly profile?: string;
    readonly id?: number;
    password: string;
    lastLogin?: Date | null;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     */
    isSuperuser?: boolean | null;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    /**
     * Designates whether the user can log into this admin site.
     */
    isStaff?: boolean | null;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    isActive?: boolean | null;
    dateJoined?: Date | null;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     */
    groups?: Array<number>;
    /**
     * Specific permissions for this user.
     */
    userPermissions?: Array<number>;
    readonly str?: string;
}

