/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Questionary } from './questionary';
import { UserProfileCreate } from './userProfileCreate';


export interface UserCreate { 
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    password: string;
    confirmPassword: string;
    questionary: Questionary;
    profile: UserProfileCreate;
}

