# Generated by Django 2.2.1 on 2019-05-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='level',
            new_name='question_level',
        ),
    ]
