# Generated by Django 2.2.1 on 2019-05-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190516_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Datetime',
        ),
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='historyline',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.History'),
            preserve_default=False,
        ),
    ]
