# Generated by Django 2.2.1 on 2019-05-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190518_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyline',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
