# Generated by Django 2.2.1 on 2019-05-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190518_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyline',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_lines', to='server.History'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='server.QuestionLevel'),
        ),
    ]
