# Generated by Django 2.2.1 on 2019-05-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190519_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.PositiveIntegerField(verbose_name='level'),
        ),
    ]
