# Generated by Django 2.2.1 on 2019-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190519_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyline',
            name='time',
        ),
        migrations.AddField(
            model_name='historyline',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
