# Generated by Django 2.2.1 on 2019-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190520_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyline',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
