# Generated by Django 2.2.1 on 2019-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
