# Generated by Django 2.2.1 on 2019-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20190522_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
