# Generated by Django 2.2.1 on 2019-06-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190613_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyline',
            name='answer',
            field=models.CharField(choices=[('left', 'left'), ('right', 'right')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyline',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
