# Generated by Django 2.2.1 on 2019-06-18 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20190613_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='valoration',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator], verbose_name='valoration'),
            preserve_default=False,
        ),
    ]
