# Generated by Django 2.2.1 on 2019-06-19 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_history_valoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='datetime',
        ),
        migrations.AddField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='history',
            name='valoration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='valoration'),
        ),
    ]
