# Generated by Django 2.2.1 on 2019-07-01 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20190619_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlevel',
            name='average_duration',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlevel',
            name='duration_threshold',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
    ]
