# Generated by Django 2.2.1 on 2019-07-11 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0020_auto_20190701_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='heigh',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'female'), ('male', 'female')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weigh',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perineal_area_pain', models.BooleanField()),
                ('vulva_pain', models.BooleanField()),
                ('clitoris_pain', models.BooleanField()),
                ('bladder_pain', models.BooleanField()),
                ('pain_frequency', models.CharField(choices=[('never', 'never'), ('rarely', 'rarely'), ('sometimes', 'sometimes'), ('many_times', 'many_times'), ('usually', 'usually'), ('always', 'always')], max_length=10)),
                ('pee_pain', models.BooleanField()),
                ('sexual_relations_pain', models.BooleanField(null=True)),
                ('pain_intensity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('stop_doing_things', models.CharField(choices=[('none', 'none'), ('a_little', 'a_little'), ('some', 'some'), ('lot', 'lot')], max_length=8)),
                ('think_symptoms', models.CharField(choices=[('none', 'none'), ('a_little', 'a_little'), ('some', 'some'), ('lot', 'lot')], max_length=8)),
                ('same_health_life', models.CharField(choices=[('charmed', 'charmed'), ('satisfied', 'satisfied'), ('dissatisfied', 'dissatisfied'), ('fatal', 'fatal'), ('very satisfied', 'very satisfied'), ('confused', 'confused'), ('discontent', 'discontent')], max_length=8)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionary',
                'verbose_name_plural': 'Questionaries',
            },
        ),
    ]
