# Generated by Django 2.2.1 on 2019-07-16 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20190711_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='weigh',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='questionary',
            name='pain_frequency',
            field=models.CharField(choices=[('never', 'never'), ('rarely', 'rarely'), ('sometimes', 'sometimes'), ('many_times', 'many_times'), ('usually', 'usually'), ('always', 'always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='pain_intensity',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='same_health_life',
            field=models.CharField(choices=[('charmed', 'charmed'), ('very_satisfied', 'very satisfied'), ('satisfied', 'satisfied'), ('confused', 'confused'), ('dissatisfied', 'dissatisfied'), ('discontent', 'discontent'), ('fatal', 'fatal')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='stop_doing_things',
            field=models.CharField(choices=[('none', 'none'), ('a_little', 'a little'), ('some', 'some'), ('lot', 'lot')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='think_symptoms',
            field=models.CharField(choices=[('none', 'none'), ('a_little', 'a little'), ('some', 'some'), ('lot', 'lot')], max_length=8),
        ),
    ]
