# Generated by Django 2.2.1 on 2019-07-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20190716_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heigh',
            new_name='height',
        ),
    ]
