# Generated by Django 2.2.1 on 2019-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20190716_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
