# Generated by Django 2.2.1 on 2019-07-17 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_auto_20190717_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='valoration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='pain_frequency',
            field=models.CharField(blank=True, choices=[('never', 'never'), ('rarely', 'rarely'), ('sometimes', 'sometimes'), ('many_times', 'many_times'), ('usually', 'usually'), ('always', 'always')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionary',
            name='pain_intensity',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionary',
            name='sexual_relations_pain',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionary',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionlevel',
            name='level',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
