# Generated by Django 2.2.1 on 2019-07-22 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20190717_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='pain_frequency',
            field=models.CharField(blank=True, choices=[('never', 'never'), ('rarely', 'rarely'), ('sometimes', 'sometimes'), ('many_times', 'many_times'), ('usually', 'usually'), ('always', 'always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='pain_intensity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='sexual_relations_pain',
            field=models.BooleanField(default=False),
        ),
    ]
