# Generated by Django 2.2.1 on 2019-07-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20190722_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
