# Generated by Django 2.2.1 on 2019-07-22 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20190722_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlevel',
            name='average_duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='questionlevel',
            name='duration_threshold',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
