# Generated by Django 2.2.1 on 2019-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_auto_20190722_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='pain_frequency',
            field=models.CharField(blank=True, choices=[('never', 'never'), ('rarely', 'rarely'), ('sometimes', 'sometimes'), ('many times', 'many times'), ('usually', 'usually'), ('always', 'always')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='same_health_life',
            field=models.CharField(choices=[('charmed', 'charmed'), ('very satisfied', 'very satisfied'), ('satisfied', 'satisfied'), ('confused', 'confused'), ('dissatisfied', 'dissatisfied'), ('discontent', 'discontent'), ('fatal', 'fatal')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='stop_doing_things',
            field=models.CharField(choices=[('none', 'none'), ('a little', 'a little'), ('some', 'some'), ('lot', 'lot')], max_length=8),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='think_symptoms',
            field=models.CharField(choices=[('none', 'none'), ('a little', 'a little'), ('some', 'some'), ('lot', 'lot')], max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 0), ('female', 1)], max_length=6, null=True),
        ),
    ]
