# Generated by Django 2.2.1 on 2019-08-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_auto_20190801_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
    ]
