# Generated by Django 2.2.1 on 2019-11-26 21:15

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20190801_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionlevel',
            options={'verbose_name': 'Question level', 'verbose_name_plural': 'Question levels'},
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=server.models.question_image_directory_path),
        ),
    ]
