/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryLineDetail { 
    readonly id?: number;
    answer?: HistoryLineDetail.AnswerEnum | null;
    duration?: number | null;
    image: string;
    correctAnswer: HistoryLineDetail.CorrectAnswerEnum;
}
export namespace HistoryLineDetail {
    export type AnswerEnum = 'left' | 'right';
    export const AnswerEnum = {
        Left: 'left' as AnswerEnum,
        Right: 'right' as AnswerEnum
    };
    export type CorrectAnswerEnum = 'left' | 'right';
    export const CorrectAnswerEnum = {
        Left: 'left' as CorrectAnswerEnum,
        Right: 'right' as CorrectAnswerEnum
    };
}

