/**
 * TFG API
 * Test description
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryLineDetail { 
    readonly id?: number;
    answer?: HistoryLineDetail.AnswerEnum | null;
    duration?: number | null;
    image: string;
    correctAnswer: HistoryLineDetail.CorrectAnswerEnum;
}
export namespace HistoryLineDetail {
    export type AnswerEnum = 'LEFT' | 'RIGHT';
    export const AnswerEnum = {
        LEFT: 'LEFT' as AnswerEnum,
        RIGHT: 'RIGHT' as AnswerEnum
    };
    export type CorrectAnswerEnum = 'LEFT' | 'RIGHT';
    export const CorrectAnswerEnum = {
        LEFT: 'LEFT' as CorrectAnswerEnum,
        RIGHT: 'RIGHT' as CorrectAnswerEnum
    };
}

